### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by namita1025** [genome/joinx#13]
When I try to compile with gcc 5.4.0 on Ubuntu, I get an error in 'Building CXX object build/src/lib/io/CMakeFiles/io.dir/StreamLineSource.cpp.o':
```
in member function 'virtual bool StreamLineSource::getline(std::__cxx11::string&)':
joinx/src/lib/io/StreamLineSource.cpp:9:34: error: cannot convert \
'std::basic_istream(char)' to 'bool' in return 
return std::getline(_in, line);
                             ^
```
Upon googling the error I find http://stackoverflow.com/questions/22330765/how-to-fix-istringstream-compiler-error which seems to imply a static casting of the return object is needed.

**Comment by Falcury** [comment]
I had this problem too, compiling with GCC 5.4.0 on Ubuntu on Windows 10. 
This change fixed the issue for me:
https://github.com/genome/joinx/pull/16/commits/ba66b5cd790d1798ce797a934df0483330429aac

**Comment by namita1025** [comment]
Thanks! I ended up using gcc 4.7.0, which solved my issue.
